<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<?php
if (isset($javascript) && $javascript)
	echo "<script type=\"text/javascript\">".$javascript."</script>\n";
?>
<script type="text/javascript" src="js/json2.js"></script>
<script type="text/javascript" src="js/mktree.js"></script>
<script type="text/javascript" src="js/main_js.php"></script>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="css/stylesheet.css">
<link rel="stylesheet" type="text/css" href="css/mktree.css">
<title>YALA</title>
</head>
<body>
<div id="treeDiv" class="treeDiv">&nbsp;</div>
<div id="mainDiv" class="mainDiv">&nbsp;</div>
