<CENTER>
<TABLE CLASS="toolbar">
<?php
	echo "<TR><TD ALIGN=\"CENTER\">[&nbsp;&nbsp;&nbsp;<A HREF=\"".MAINFILE."?do=choose_entrytype\" TARGET=\"right\">New</A>&nbsp;&nbsp;&nbsp;]</TD><TD ALIGN=\"CENTER\">[&nbsp<A HREF=\"".MAINFILE."?do=search_form\" TARGET=\"right\">Search</A>&nbsp;]</TD></TR>\n";
	echo "<TR><TD ALIGN=\"CENTER\">[&nbsp;<A HREF=\"".MAINFILE."?do=logout\" TARGET=\"right\">Logout</A>&nbsp;]</TD><TD ALIGN=\"CENTER\">[&nbsp;<A HREF=\"javascript:parent.left.location.reload(); parent.right.location.href='main.php?do=reloadschema';\">Refresh</A>&nbsp;]</TD></TR>\n";
?>
</TABLE>
</CENTER>
<HR>
